business:
  info: Business Microservice Development
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/qa
    username: postgres
    password: qwer
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
	mail:
    host: smtp.gmail.com
    port: 587
    username: it.chhaya@gmail.com
    password: duuf wtgf nobv hggc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
